mysite/app/urls.py
from django.conf.urls import url
from .views import AuthorsView, BooksView, AuthorsDetailView, BooksDetailView
app_name = "authors"

urlpatterns = [
    url(r'^authors/$', AuthorsView.as_view()),
    url(r'^books/$', BooksView.as_view()),
    url(r'^authors/(?P<pk>\d+)/$', AuthorsDetailView.as_view()),
    url(r'^books/(?P<pk>\d+)/$', BooksDetailView.as_view()),
]

mysite/authors/urls.py
from . import views

from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^$', AuthorListView.as_view(), name='author-home'),
    url(r'^post/(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='author-detail'),
    url(r'^search/$', AuthorSearchView.as_view(), name='author-search')
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from users.views import profile
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('blog.urls')),
    url(r'^register/', include('users.urls')),
    url(r'^author/', include('authors.urls')),
    url(r'^review/', include('review.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    url(r'^profile/', profile, name='profile'),
    url(r'^app/', include('app.urls')),
]

mysite/authors/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.urls import reverse


class Authors(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    biography = models.TextField(max_length=1000)

    class Meta:
        ordering = ['last_name']

    def __str__(self):
        return "{0}, {1}".format(self.last_name, self.first_name)

    def get_absolute_url(self):
        return reverse('auth_id',
                       kwargs={
                           'auth_id': self.pk
                       }
                       )

mysite/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from authors.models import Authors


class Books(models.Model):

    book_name = models.CharField(max_length=255)
    description = models.TextField(max_length=2000)
    authors = models.ManyToManyField(Authors)

    def __str__(self):
        return self.book_name

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['book_name']

mysite/authors/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db.models import Q
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
)
from authors.models import Authors
from django import forms


class SearchForm(forms.Form):
    q = forms.CharField()


class AuthorListView(ListView):
    model = Authors
    template_name = 'authors/authors_list.html'
    context_object_name = 'posts'
    ordering = ['-last_name']
    paginate_by = 10


class AuthorDetailView(DetailView):
    model = Authors


class AuthorSearchView(ListView):
    paginate_by = 10
    context_object_name = 'posts'
    ordering = ['-last_name']

    def get_queryset(self):
        q = self.request.GET.get("q")
        return Authors.objects.filter(Q(first_name__icontains=q) | Q(last_name__icontains=q))

    def get_context_data(self, *args, **kwargs):
        context = super(AuthorSearchView, self).get_context_data(*args, **kwargs)
        context["q"] = 'q={0}&'.format(self.request.GET.get("q"))
        return context


def author_search(request):
    return render(request, 'authors/author_search.html', {'title': 'Author Search'})

mysite/authors/templates/authors/authors_detail.html
{% extends "blog/base.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <h2 class="article-title">{{ object.first_name }} {{ object.last_name }}</h2>
      <p class="article-content">{{ object.biography }}</p>
      <p> Books:
{% for author in object.books_set.all %}
   " {{ author.book_name }} "
 {% endfor %}
</p>
    </div>
  </article>
{% endblock content %}

mysite/authors/templates/authors/authors_list.html
{% extends "blog/base.html" %}
{% block content %}
 <div class="media-body">
            <h3>Search Author</h3>
     <form action="{% url 'author-search' %}" metod="get">
         <input type="search" placeholder="Write search author..." name="q" class="form-control">
         <button type="submit">
             <span ></span>
         </button>
<hr>
     </form>
          </div>
    {% for post in posts %}
          <div class="media-body">
            <h2><a class="article-title" href="{% url 'author-detail' post.pk %}">{{ post.last_name}} {{ post.first_name}}</a></h2>
            <p class="article-content">{{ post.biography|linebreaks|truncatewords:20 }}</p>
          </div>
<hr>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-danger mb-4" href="?{{ q }}page=1">First</a>
        <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}