mysite/app/urls.py
from django.conf.urls import url
from .views import AuthorsView, BooksView, AuthorsDetailView, BooksDetailView
app_name = "authors"

urlpatterns = [
    url(r'^authors/$', AuthorsView.as_view()),
    url(r'^books/$', BooksView.as_view()),
    url(r'^authors/(?P<pk>\d+)/$', AuthorsDetailView.as_view()),
    url(r'^books/(?P<pk>\d+)/$', BooksDetailView.as_view()),
]

mysite/blog/urls.py
from . import views
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'^about/$', about, name='about'),
    url(r'^$', PostListView.as_view(), name='blog-home'),
    url(r'^post/(?P<pk>\d+)/$', PostDetailView.as_view(), name='post-detail'),
    url(r'^post/new/$', PostCreateView.as_view(), name='post-create'),
    url(r'^post/(?P<pk>\d+)/update/$', PostUpdateView.as_view(), name='post-update'),
    url(r'^post/(?P<pk>\d+)/delete/$', PostDeleteView.as_view(), name='post-delete'),
    url(r'^search_book/$', BooksSearchView.as_view(), name='books-search')
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from users.views import profile
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('', include('blog.urls')),
    url(r'^register/', include('users.urls')),
    url(r'^author/', include('authors.urls')),
    url(r'^review/', include('review.urls')),
    url(r'^comments/', include('comments.urls')),
    url(r'^login/', auth_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    url(r'^logout/', auth_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    url(r'^profile/', profile, name='profile'),
    url(r'^app/', include('app.urls')),
]

mysite/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse
from authors.models import Authors


class Books(models.Model):

    book_name = models.CharField(max_length=255)
    description = models.TextField(max_length=2000)
    authors = models.ManyToManyField(Authors)

    def __str__(self):
        return self.book_name

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ['book_name']

mysite/comments/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import reverse
from review.models import Review
from django.contrib.auth import get_user_model
from django.db import models
User = get_user_model()


class Comments(models.Model):

    user = models.ForeignKey(
        User,
        verbose_name="Author od comment",
        on_delete=models.CASCADE
    )
    text = models.TextField(max_length=1000)
    review = models.ForeignKey(
        Review,
        on_delete=models.CASCADE,
    )

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.review.book.pk})

    class Meta:
        ordering = ['text']

    def __str__(self):
        return '{0} {1} '.format(self.user.first_name, self.user.last_name)

mysite/review/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from blog.models import Books
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
User = get_user_model()


class Review(models.Model):

    text = models.TextField(max_length=5000)
    book = models.ForeignKey(Books, on_delete=models.CASCADE)
    user = models.ForeignKey(
        User,
        verbose_name="Author od comment",
        on_delete=models.CASCADE
    )

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.book.pk})

    class Meta:
        ordering = ['book']

    def __str__(self):
        return '{0} {1} {2}'.format(self.user.first_name, self.user.last_name, self.book.book_name)

mysite/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from .models import Books
from django.db.models import Q


def about(request):
    return render(request, 'blog/about.html', {'title': 'About'})


class PostListView(ListView):
    model = Books
    template_name = 'blog/books_list.html'
    context_object_name = 'posts'
    ordering = ['-book_name']
    paginate_by = 10


class PostDetailView(DetailView):
    model = Books


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Books
    fields = '__all__'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreateView, self).form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Books
    fields = '__all__'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostUpdateView, self).form_valid(form)

    def test_func(self):
        post = self.get_object()
        auths = post.authors.all()
        for auth in auths:
            if auth.first_name == self.request.user.first_name and auth.last_name == self.request.user.last_name:
                return True
        return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Books
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        auths = post.authors.all()
        for auth in auths:
            if auth.first_name == self.request.user.first_name and auth.last_name == self.request.user.last_name:
                return True
        return False


class BooksSearchView(ListView):
    paginate_by = 10
    context_object_name = 'posts'
    ordering = ['-last_name']

    def get_queryset(self):
        q = self.request.GET.get("q")
        return Books.objects.filter(Q(book_name__icontains=q))

    def get_context_data(self, *args, **kwargs):
        context = super(BooksSearchView, self).get_context_data(*args, **kwargs)
        context["q"] = 'q={0}&'.format(self.request.GET.get("q"))
        return context

mysite/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

mysite/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'blog/CSS/main.css' %}">

    {% if title %}
        <title>Django Blog - </title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{%url 'blog-home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{%url 'blog-home' %}">Home</a>
              <a class="nav-item nav-link" href="{%url 'about' %}">About</a>
                {% if request.user.groups.all.0.name == 'Authors' %}
                 <a class="nav-item nav-link" href="{% url 'post-create' %}">Create Book</a>
                {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                  {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
              <ul class="list-group">
                <a class="nav-item nav-link"   href="{% url 'author-home' %}"><li class="list-group-item list-group-item-light">Authors</li></a>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

mysite/blog/templates/blog/books_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.book_name }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.pk %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

mysite/blog/templates/blog/books_detail.html
{% extends "blog/base.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        {% for auth in object.authors.all %}
        {% if auth.first_name == user.first_name and auth.last_name == user.last_name %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.pk %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.pk %}">Delete</a>
          </div>
        {% endif %}
        {% endfor %}
      </div>
      <h2 class="article-title">{{ object.book_name }}</h2>
      <p class="article-content">{{ object.description }}</p>
      <p> Authors:
      {% for author in object.authors.all %}
         " {{ author.first_name }} {{ author.last_name }} "
      {% endfor %}

</p>
         {% if request.user.groups.all.0.name == 'Users' %}
         <small class="text-muted">
           <p align="right"> <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'review-create' object.pk %} ">Add review</a></p>
        </small>
{% endif %}
    </div>
  </article>

       {% for review in object.review_set.all %}
 <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
    <h3>Review</h3>
        {% if review.user == user  %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'review-update' review.pk %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'review-delete' review.pk %}">Delete</a>
          </div>
        {% endif %}

      </div>
      <h4 class="article-title">{{ review.user }}</h4>
      <p class="article-content">{{ review.text }}</p>
        {% if request.user.groups.all.0.name == 'Users' %}
        <p align="right"> <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'comments-create' review.pk %} ">Add comment</a></p>
        {% endif %}
        <hr>
        <h4>Comments</h4>
        {% for comment in review.comments_set.all %}
        <hr>
 <article class="media content-sections">
    <div class="media-body">
      <div class="article-metadata">
        {% if comment.user == user  %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'comments-update' comment.pk %}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'comments-delete' comment.pk %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h4 class="article-title">{{ comment.user }}</h4>
      <p class="article-content">{{ comment.text }}</p>


    </div>
  </article>

 {% endfor %}

    </div>
  </article>
 {% endfor %}


{% endblock content %}

mysite/blog/templates/blog/books_form.html
{% extends "blog/base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

mysite/blog/templates/blog/books_list.html
{% extends "blog/base.html" %}
{% block content %}
 <div class="media-body">
            <h3>Search Books</h3>
     <form action="{% url 'books-search' %}" metod="get">
         <input type="search" placeholder="Write search author..." name="q" class="form-control">
         <button type="submit">
             <span ></span>
         </button>
<hr>
     </form>
          </div>
    {% for post in posts %}
          <div class="media-body">
            <h2><a class="article-title" href="{% url 'post-detail' post.pk %}">{{ post.book_name }}</a></h2>
            <p class="article-content">{{ post.description|linebreaks|truncatewords:20 }}</p>
          </div>
<hr>
    {% endfor %}
    {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-danger mb-4" href="?{{ q }}page=1">First</a>
        <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-danger mb-4" href="?{{ q }}page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

    {% endif %}
{% endblock content %}